# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [3]:
# Create a 1-dimensional NumPy array using np.array()
array_1 = np.array([1, 2, 3])
# Create a 2-dimensional NumPyarray using np.array()
array_2 = np.array([[1, 2, 3], 
                    [1, 2, 3]])
# Create a 3-dimensional Numpy array using np.array()
array_3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.shape, array_1.ndim, array_1.dtype, array_1.dtype

((3,), 1, dtype('int32'), dtype('int32'))

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

myFrame = pd.DataFrame(array_2)
myFrame

0  1  2
0  1  2  3
1  1  2  3

In [10]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
array_ones = np.ones((7, 2, 3))
array_ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0, 100, 3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array = np.random.randint(0, 10, size = (7, 2))
array

array([[4, 9],
       [7, 0],
       [7, 5],
       [1, 6],
       [6, 9],
       [8, 2],
       [7, 4]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array = np.random.random((3, 5))
array

array([[0.35367861, 0.84887728, 0.35092541, 0.5557968 , 0.21036526],
       [0.00422878, 0.15825982, 0.26197359, 0.7546925 , 0.69960552],
       [0.08282206, 0.5919231 , 0.66667827, 0.118639  , 0.47004438]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size = (4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

array = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [25]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [26]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2, :2]

array([[9, 1],
       [5, 3]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a1 = np.random.randint(0, 10, size = (3, 5))
ones = np.ones((3, 5))

In [34]:
# Add the two arrays together
a1 + ones

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [35]:
# Create another array of ones of shape (5, 3)
a2 = np.ones((5, 3))

In [36]:
# Create another array of ones of shape (3, 5)
a3 = np.ones((3, 5))

In [38]:
# Subtract the new array of ones from the other most recent array
a3 - a2.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# Multiply the ones array with the latest array
a2 * a3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Take the latest array to the power of 2 using '**'
a3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Do the same thing with np.square()
a3 = np.square(a3)
a3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# Find the mean of the latest array using np.mean()
np.mean(a3)

1.0

In [45]:
# Find the maximum of the latest array using np.max()
np.max(a3)

1.0

In [46]:
# Find the minimum of the latest array using np.min()
np.min(a3)

1.0

In [47]:
# Find the standard deviation of the latest array
np.std(a3)

0.0

In [48]:
# Find the variance of the latest array
np.var(a3)

0.0

In [51]:
# Reshape the latest array to (3, 5, 1)
a3.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [52]:
# Transpose the latest array
a3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(0, 10, size = (3, 3))
a2 = np.random.randint(0, 10, size = (3, 2))


In [54]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [56]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[6, 9, 9],
       [6, 8, 8],
       [0, 1, 7]])

In [58]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[1, 0, 2],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

0

In [60]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

8

In [61]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1, axis = 1)

array([0, 0, 0], dtype=int64)

In [62]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a1, axis = 0)


array([2, 2, 2], dtype=int64)

In [63]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.45788508, -1.68428738,  0.32684522, -0.08111895,  0.46779475],
       [ 0.73612235, -0.77970188, -0.84389636, -0.15053386, -0.96555767],
       [ 0.15048908, -0.11342125,  2.63352822, -1.02509089, -0.78204783]])

In [64]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])